# Generated by Django 6.0.6 on 2026-06-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Kabinet raqami')),
                ('floor', models.PositiveIntegerField(verbose_name='Qavat')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kabinet (qabul xonasi)',
                'verbose_name_plural': 'Kabinetlar (qabul xonalari)',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Palata nomi')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Palata raqami')),
                ('ward_type', models.CharField(choices=[('general', 'Umumiy palata'), ('vip', 'VIP palata'), ('icu', 'Reanimatsiya'), ('surgery', 'Jarrohlikdan keyingi'), ('pediatric', 'Bolalar palatasi'), ('maternity', "Tug'uruqxona")], max_length=20, verbose_name='Turi')),
                ('floor', models.PositiveIntegerField(verbose_name='Qavat')),
                ('total_beds', models.PositiveIntegerField(verbose_name="Jami o'rinlar")),
                ('price_per_day', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Kunlik narx')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Palata (yotish bo'limi)",
                'verbose_name_plural': "Palatalar (yotish bo'limi)",
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=10, verbose_name="O'rin raqami")),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Yotmoqda'), ('discharged', 'Chiqarilgan')], default='active', max_length=20)),
                ('diagnosis', models.TextField(verbose_name='Tashxis')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='rooms.ward')),
            ],
            options={
                'verbose_name': 'Bemor yotishi',
                'verbose_name_plural': 'Bemor yotishlari',
            },
        ),
    ]
