# Generated by Django 6.0.6 on 2026-06-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Maosh'), ('medicine', 'Dori-darmon'), ('equipment', 'Jihozlar'), ('utilities', 'Kommunal'), ('maintenance', "Ta'mirlash"), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Summa')),
                ('date', models.DateField(verbose_name='Sana')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=10, verbose_name='Tur')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Summa')),
                ('description', models.CharField(max_length=300, verbose_name='Tavsif')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.treatment')),
            ],
            options={
                'verbose_name': 'Kassa yozuvi',
                'verbose_name_plural': 'Kassa yozuvlari',
                'ordering': ['-date'],
            },
        ),
    ]
