# Generated by Django 6.0.6 on 2026-06-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Dori kategoriyasi',
                'verbose_name_plural': 'Dori kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('piece', 'Dona'), ('pack', 'Paket'), ('bottle', 'Shisha'), ('box', 'Quti'), ('ml', 'ml'), ('g', 'gramm')], default='piece', max_length=10, verbose_name="O'lchov birligi")),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Sotish narxi (so'm)")),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Zaxiradagi miqdor')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Minimal zaxira')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Dori / Mahsulot',
                'verbose_name_plural': 'Dorilar / Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Kelish narxi (dona uchun)')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Yetkazuvchi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'Dori kelishi',
                'verbose_name_plural': 'Dori kelishlari',
                'ordering': ['-date'],
            },
        ),
    ]
