# Generated by Django 6.0.6 on 2026-06-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0003_doctorservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('position', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Shifokor'), ('nurse', 'Hamshira'), ('cleaner', 'Farrosh'), ('other', 'Boshqa xodim')], max_length=20, verbose_name='Lavozim')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('monthly_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Oylik maosh')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ishga kirgan sana')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_record', to='doctors.doctor', verbose_name="Bog'liq shifokor profili")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['position', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="To'langan summa")),
                ('period', models.CharField(max_length=20, verbose_name='Davr (oy-yil)')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='accounts.staff')),
            ],
            options={
                'verbose_name': "Maosh to'lovi",
                'verbose_name_plural': "Maosh to'lovlari",
                'ordering': ['-paid_at'],
                'unique_together': {('staff', 'period')},
            },
        ),
    ]
