# Generated by Django 6.0.6 on 2026-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, verbose_name='Shikoyat / sabab')),
                ('status', models.CharField(choices=[('booked', 'Band qilingan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Navbat (qabul)',
                'verbose_name_plural': 'Navbatlar (qabullar)',
                'ordering': ['-created_at'],
            },
        ),
    ]
