# Generated by Django 6.0.6 on 2026-06-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=300, verbose_name='Operatsiya nomi')),
                ('operation_room', models.CharField(max_length=50, verbose_name='Operatsiya xonasi')),
                ('scheduled_date', models.DateTimeField(verbose_name='Vaqti')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('lead_surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Operatsiya',
                'verbose_name_plural': 'Operatsiyalar',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
