# Generated by Django 6.0.6 on 2026-06-20 11:08

import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=patients.models.generate_patient_id, max_length=20, unique=True, verbose_name='Bemor ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jinsi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Qon guruhi')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergiyalar')),
                ('has_booked', models.BooleanField(default=False, verbose_name='Birinchi navbatni band qilganmi')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Tashxis')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Jami narx')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_price_snapshot', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Konsultatsiya narxi (saqlangan)')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='appointments.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Davolash yozuvi',
                'verbose_name_plural': 'Davolash yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Birlik narxi (saqlangan)')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to='patients.treatment')),
            ],
            options={
                'verbose_name': 'Ishlatilgan mahsulot',
                'verbose_name_plural': 'Ishlatilgan mahsulotlar',
            },
        ),
    ]
