# Generated by Django 6.0.6 on 2026-06-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorservice'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='extra_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctorservice', verbose_name="Qo'shimcha ko'rik xizmati"),
        ),
        migrations.AddField(
            model_name='treatment',
            name='extra_service_price_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Xizmat narxi (saqlangan)'),
        ),
    ]
