# Generated by Django 6.0.3 on 2026-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_treatment_extra_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='receipt_issued',
            field=models.BooleanField(default=False, verbose_name='Chek berilganmi'),
        ),
    ]
