# Generated by Django 6.0.6 on 2026-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='1. Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='2. Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='3. Telefon')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='4. Jinsi')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='6. Ish tajribasi (yil)')),
                ('consultation_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='7. Konsultatsiya narxi')),
                ('photo', models.ImageField(blank=True, upload_to='doctors/', verbose_name='9. Rasmi')),
                ('bio', models.TextField(blank=True, verbose_name="10. Qisqacha ma'lumot")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Band qilinganmi')),
            ],
            options={
                'verbose_name': "Bo'sh vaqt",
                'verbose_name_plural': "Bo'sh vaqtlar",
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mutaxassislik')),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
            },
        ),
    ]
