# Generated by Django 6.0.6 on 2026-06-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctors.doctor')),
            ],
            options={
                'verbose_name': "Ko'rik xizmati",
                'verbose_name_plural': "Ko'rik xizmatlari",
            },
        ),
    ]
